//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPT1.Model.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SMEntities : DbContext
    {
        private static SMEntities _context;
        public SMEntities()
            : base("name=smEntities")
        {
        }
        public static SMEntities GetContext()
        {
            if (_context == null)
                _context = new SMEntities();

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Characteristics> Characteristics { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersRoles> UsersRoles { get; set; }
        public virtual DbSet<v_PopularProducts> v_PopularProducts { get; set; }
        public virtual DbSet<v_ReservedProducts> v_ReservedProducts { get; set; }
    
        public virtual int GetPopularProducts(Nullable<int> limit_count)
        {
            var limit_countParameter = limit_count.HasValue ?
                new ObjectParameter("limit_count", limit_count) :
                new ObjectParameter("limit_count", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetPopularProducts", limit_countParameter);
        }
    }
}
