//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPT1.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Characteristics
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Characteristics()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int CharacteristicsID { get; set; }
        public string Description { get; set; }
        public decimal Power_KWT_ { get; set; }
        public decimal EnergyConsumption_KWT_H_ { get; set; }
        public int Guaranty_Years_ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products> Products { get; set; }
    }
}
