//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPT1.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersRoles
    {
        public int URID { get; set; }
        public int UserID { get; set; }
        public int RoleID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual Users Users { get; set; }
    }
}
