//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPT1.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_PopularProducts
    {
        public string PName { get; set; }
        public string CName { get; set; }
        public Nullable<int> ВсегоПродано { get; set; }
        public Nullable<int> КоличествоПродаж { get; set; }
    }
}
